export let ARTICLES = [
  {
    id: 1,
    title: "A Catholic's Call to Evangelize",
    route: "catholic-call-to-evangelize",
    author: "Matt Sebastian",
    date: "07/11/2021",
    text: ["There is a dire need to evangelize in a world that is steadily going down in sin and losing its moral values. The call to evangelize is the overarching mission of the Church and is as much a call to the Religious Clergy as it is to the laity. However, the average Catholic is faced with the dilemma of being mistaken for proselytizing when attempting to evangelize and tends to hold back. Whereas in reality there are several ways to evangelize without proselytizing. For example Having a loving attitude to a neighbor impresses them and leaves them wondering what is the reason for our love and hope. (Cf 1 Corinthians 13:4-5 “Love is patient and kind; love is not jealous or boastful; it is not arrogant or rude”). But in a gentle way, our Lord directs us to give an answer to anyone asking us to explain the reason for our hope (cf 1 Peter 3:15 “Always be ready to make your defense to anyone who demands from you an accounting for the hope that is in you;”).",
          "On learning the core mandate of the Church being that of bearing witness to Christ and spreading the Gospel, it is imperative that the Catholics treat evangelization with dire urgency. To this end, evangelization can be creatively executed, and doesn’t always have to be preaching from the pulpit. Personally, I feel some of the most effective forms of evangelization are one-one when you share what God has done for you in your life with anyone who is open to listen. Your testimony of how God worked in your life and caused a conversion can be a powerful way to evangelize. Sometimes our actions can lead people to experience Christ. Probably the greatest example is Mother Teresa who worked amongst the poor underprivileged Hindu kids in the streets of Calcutta, India, and by her works led others to come to know Christ. In summary, Catholics – both clergy and laity need to treat evangelization with a sense of urgency. They need to adopt to creative ways to evangelize as mentioned above, in alignment with directives of the Church as in Pope Francis’ exhortation ‘Evangelii Gaudium’ that urges the Church to understand itself as a \"community of missionary disciples\", who need to “embark on a new chapter of evangelism\"."]
  },
  {
    id: 2,
    title: "Does Suffering have a deeper meaning in my life?",
    route: "suffering-deeper-meaning",
    author: "Matt Sebastian",
    date: "07/11/2021",
    text: ["The fact that God gave us His only begotten Son, who though fully Divine, yet came down as fully human, to experience humanity’s frailty while remaining sinless, was in itself a supreme act of humility and sacrifice. This element of Christ’s sacrifice continued all through His life, in His suffering, and Death on the Cross when He took on all of humankind’s sin and offered it for the redemption of mankind. In his death as paschal sacrifice, he overcame death by resurrection and ascension into Heaven, thereby laying the cornerstone for humanity’s salvation into eternal life or the Kerygma (Greek) as defined by St. Paul. We as Christians are called to embrace this Paschal Christology knowing that in our suffering we unite ourselves to Christ’s suffering on the Cross, so we find redemptive meaning in the suffering, ultimately intensifying our quest for God and leading us to salvation. My suffering can also be redemptive for others – and when I suffer my will can be joined to Christ’s will – and completes Jesus’ suffering on the Cross, just as the Church (His mystical body) completes the redemptive work of Christ (cf. Colossians 1:24). Likewise, all men and women, regardless of whether they are Christian or non-Christian, unite their struggles and suffering with Christ’s suffering, and without them necessarily knowing, Christ silently suffers with them. A Christian says ‘We don’t suffer alone. God suffers with us.’ Christ meets everyone in the darkest moments of life, regardless of where they are in their spiritual journey, whether they have professed their faith in Him, or whether they are non-Christian. He turns all suffering for the good of all those who are called according to His purpose (cf. Romans 8:28).",
           "Further, Paschal Christology expounds that all humans partake in the paschal mystery of Christ when they look beyond themselves and develop a calling to be with their neighbor in their suffering, just as the Good Samaritan did. We don’t have to say much, just unleash love from our hearts for those suffering and be there for them. This transformation of human attitude is made possible by embracing the Christian faith in the Church. But, can work well outside the Church as well (cf. Acts 17:23), so long as people can embrace similar corporal works of mercy such as feeding the poor, caring for the sick, visiting the imprisoned etc. Christ as a role model and His teachings on the beatitudes thereby become a standard for all humanity to aspire to when they partake in such works."
    ]
  },
  {
    id: 3,
    title: "How does The Church address the need of our times?",
    route: "church-need-of-our-times",
    author: "Matt Sebastian",
    date: "07/11/2021",
    text: [
      "The greatest cause for concern in the modern world is its tendency to drift further away from God, which has manifested in rampant spread of sins that has threatened the disintegration of the basic unit of society – the family. Resultant effects are scant regard (disrespect) for life as in abortion and euthanasia, alteration to the basic structure of the family as in escalating divorce rates and infidelity /promiscuity that dishonor the sacrament of marriage. Byproducts of a broken family system is a society that is aggressive, nurtures unforgiveness and hates peace and harmony. The resultant manifestations can be seen in societal discord and a 'Godless trend' leading to atheism, relativism and agnosticism affecting many parts of the world today.",
      "The Church can address these needs and rebuild the moral framework of the society by emphasizing the need to lead good Christian lives and steer its parishioners toward intentional discipleship. Further, the Church must emphasize the importance of reaching out to those who are marginalized in the society, while equipping its clergy, religious and laity to spread the Good News to the masses. The Church’s focus on evangelization along with corporal and spiritual works of mercy can have a global impact on the spread of awareness of God and Godly virtues. This can lead to restoration of the basic family unit thereby orienting society toward God’s plan of goodness and peace. To this end, the Church can also train and hone leaders among its religious and laity to engage with policy makers in areas of social justice and framing policies that respect the dignity of life and advocate alignment with Godly virtues. Finding the lost sheep is primary on our Lord’s heart as explained in the parable of the lost sheep in Luke 15:1-7. To save a culture that is being lost, the Church must earnestly seek the intervention of the Holy Spirit in its efforts to evangelize and pray for salvation of all with its overarching goal being that ‘no soul should be lost’."
    ]
  },
  {
    id: 4,
    title: "The Church is the 'Universal Sacrament of Salvation'",
    route: "universal-sacrament-of-salvation",
    author: "Matt Sebastian",
    date: "07/11/2021",
    text: [
      "The Church is called the “universal sacrament of salvation” in Lumen Gentium 48, because it was established as the Body of the risen Christ by the power of His Holy Spirit. Jesus is the Word who became flesh, who walked the earth, living as one among us, and who experienced the human frailty while remaining sinless and unblemished. Just as Jesus was the Word, in dying He gave us His body as the ultimate act of love, so He remains in communion with us and save us from sin. This then is our daily saving grace that renews us and gives us the spiritual nourishment to go on with our daily lives here on earth. By hence nourishing us with His own body, he makes us partakers of His Divine plan of salvation and wants all of mankind to be drawn to His body as part of this plan.",
      "This leads us to an important realization that our temporal lives on earth are really meant to work out our salvation through His Church with the help of His Holy Spirit. Just as important as this is for us, this then is also true for the salvation of all mankind, whether they realize it or not. To this end, Jesus has started His restoration plan for the salvation of all mankind, by sending down His Holy Spirit on all the world - Jews and Gentiles alike, so everyone be drawn to Christ and His Church and be nourished by His Body and Blood. Cf. CCC 737: “The Spirit prepares men and goes out to them with his grace, in order to draw them to Christ.” The Holy Spirit also inspires His Church (i.e. us) to work for the common good of restoration of His Church, by gifting us with charisms for evangelization and drawing people into Christ’s plan of salvation. Cf. CCC 738: “Thus the Church's mission is not an addition to that of Christ and the Holy Spirit, but is its sacrament: in her whole being and in all her members, the Church is sent to announce, bear witness, make present, and spread the mystery of the communion of the Holy Trinity.”. In summary, the core mission of the Church is to bear witness to Christ universally, to all the corners of the world, and proclaim the Gospel and Jesus’ plan for salvation of all mankind."
    ]
  },
  {
    id: 5,
    title: "The Charisms of the Holy Spirit and Evangelization",
    route: "charisms-of-holy-spirit",
    author: "Matt Sebastian",
    date: "07/11/2021",
    text: [
      "“Charisms” of the Holy Spirit are gratuitous gifts given by the Holy Spirit to build up the Church. The early Church in its first three hundred plus years, was a wholly charismatic church, and the manifestations of the Holy Spirit were abundant in promulgating the Gospel and expansion of the Church to the far corners of the world. In recent times, specifically (post Vatican II ) in the 1960’s, there has been a call for ‘New Evangelization’ and the charisms of the Holy Spirit to be exercised in new ways for the renewal of the Church. Pope John Paul II on December 11, 1979, addressing the international leaders of the Renewal about the importance of Charismatic Renewal, said “I am convinced that this movement is a very important component of the entire renewal of the Church. This was my own spiritual initiation, so I can understand all these charisms. They are all part of the richness of the Lord. I am convinced that this movement is a sign of his action.” More recently, Pope Francis in his address at St. Peter’s Square on July 3, 2015 quoted Pope Paul VI from the Mass on Pentecost in 1975 where he thanks Cardinal Léon-Joseph Suenens, the great defender of Charismatic Renewal as follows: “In the name of the Lord I thank you for having brought the Charismatic Renewal into the heart of the Church”. In my own Parish community, we see several charisms at work, especially teaching, generosity, compassion, healing, evangelization, and leadership to name few of the common ones. Whether it be serving in one of the 130+ ministries in our Parish – e.g. Eucharistic Ministry, Intercessory Prayer Ministry, Retreat Ministry, Charismatic Prayer Ministry, Adult Faith Formation et al. these charisms are at work for the common good and building up of the Church. This enables us as a diverse and hospitable Catholic Community to pray, serve and spread the Gospel with joy. Further, these charisms also enable us to realize our higher calling as Catholic Christians by:",
      "<li> Allowing the Holy Spirit to speak powerfully to our hearts and grow us toward intentional discipleship. </li <li> Deepening our prayer lives and dependence on the Holy Spirit in all aspects of our lives.</li> <li> Filling our hearts with zeal to bring others to Christ by spreading the Gospel.</li>"
    ]
  },
  {
    id: 5,
    title: "Relating to an Agnostic",
    route: "relating-to-agnostic",
    author: "Matt Sebastian",
    date: "07/11/2021",
    text: [
      "The person I recall when I think about someone who is not necessarily Christian, but has good moral values, is a young man who was my next door neighbor for many years. Although not Christian, but belonging to another faith, and even being agnostic to that faith for most part, he displayed rare prudence, courage,temperance and justice, exuding all the cardinal virtues. He really surprised me in that he had this innate goodness about him, despite being agnostic and living with no set tenets of structured faith to guide him. After having known him for a while, I brought up the subject of Christianity and Jesus, and told him my reason for faith. Although he never challenged my faith, and was receptive to most things that I said, he was not particularly inclined to go about a set religion. It looked like he was against organized religion but supported the concepts of Christianity by and large. During conversations, I could relate some of his values with Christian moral truths and was further able to engage in dialogue about the core theological virtues of faith, hope and love. At the end of the day we would always agree on certain areas and choose to agree even on the things we disagreed on. I saw a lot of nobility in his values and came to respect him for who he was. I continue to pray for him to come to know our Lord, because I know that faith is a God-given gift to man as much as it is man's response to that gift of God's revelation."
    ]
  }
];

